apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: prediction-manager-dataset-store
  namespace: kubeflow
  labels:
    app: prediction-manager
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 20Gi
