server {
    listen 80;
    root /usr/share/nginx/html;
    index index.html;

    location /fedit/ {
        alias /usr/share/nginx/html/;
        try_files $uri $uri/ /fedit/index.html;
    }

    location /fedit {
        return 301 /fedit/;
    }
}
